// Custom Cloudflare Worker entry (wrangler `main`). Wraps the OpenNext-generated
// fetch handler and adds a scheduled() handler for the native cron triggers.
//
// The fetch path is a BYTE-IDENTICAL passthrough to the generated handler — the only
// addition is scheduled(). See wrangler.jsonc `triggers.crons`.
//
// WHY scheduled() routes each cron through openNext.fetch instead of calling the
// in-process runner (runScheduledCron) directly:
// The cron runners read getCloudflareContext() (env + a per-request neon Pool, see
// lib/db.ts). OpenNext populates that context from an AsyncLocalStorage that is set
// ONLY inside runWithCloudflareRequestContext — which runs ONLY on the fetch path.
// A scheduled() event has no such scope, so a direct runner call throws
// (getCloudflareContext) and falls back to the node-postgres singleton, which hangs
// on workerd. Invoking openNext.fetch with a synthetic Request is a direct in-process
// call (no network, no service binding) that runs the context wrapper for free, so the
// cron route executes exactly as in a real request and each runner gets a valid Pool.

// @ts-expect-error — generated by `opennextjs-cloudflare build`, absent at typecheck time
import openNextWorker from "./.open-next/worker.js";

interface OpenNextWorker {
  fetch(request: Request, env: unknown, ctx: unknown): Promise<Response>;
}
const worker = openNextWorker as OpenNextWorker;

// cron pattern → in-process cron route (schedules mirror apps/www/vercel.json; all
// four runners are in-process as of server-lib/cron.ts). Keep in sync with
// wrangler.jsonc `triggers.crons`.
const CRON_TO_PATH: Record<string, string> = {
  "0 * * * *": "/api/internal/cron/stalled-tasks",
  "*/1 * * * *": "/api/internal/cron/scheduled-tasks",
  "*/10 * * * *": "/api/internal/cron/queued-tasks",
  "*/30 * * * *": "/api/internal/cron/automations",
};

export default {
  // Byte-identical passthrough — no wrapping logic on the request path.
  fetch: worker.fetch,

  async scheduled(
    event: { cron: string },
    env: { CRON_SECRET: string },
    ctx: { waitUntil(promise: Promise<unknown>): void },
  ): Promise<void> {
    const path = CRON_TO_PATH[event.cron];
    if (!path) {
      console.log(`[scheduled] no cron route for '${event.cron}' — skipping`);
      return;
    }
    // Route through the fetch handler so runWithCloudflareRequestContext populates the
    // Cloudflare context; the route's Bearer guard checks env.CRON_SECRET.
    const request = new Request(`https://cron.internal${path}`, {
      method: "GET",
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(worker.fetch(request, env, ctx));
  },
};
